### PR TITLE
update deprecated htmlAttributes to hProperties

### LINKED ISSUE #40: Links are not added to headings
I just tried the example from the README, and no links are added to the html.

I've created a repo demonstrating the issue https://github.com/rigor789/remark-autolink-headings-issue

Is there something I missed? 

In the meantime I'll dig deeper, and submit a PR if I figure it out

Edit:

Looks like `htmlAttributes` has been deprecated and replaced with `hProperties`.

`remark-slug` has been updated to use `hProperties` and this needs to be updated as well.

PR is on it's way.

### PR DESCRIPTION
**Pull request by rigor789**
Fixes #40

### CODE REVIEW

**Comment by rigor789** [comment]
Hey @ben-eb, when you get the chance could you please take a look at this PR? 

Cheers!

**Comment by thetutlage** [comment]
Dude any plans to fix this?

**Comment by thetutlage** [comment]
I am maintaining a fork here https://github.com/thetutlage/remark-autolink-headings. 

I updated all the dev dependencies and dependencies.

1. Removed eslint and using standard ( personal preference )
2. Using `babel-preset-env` over `es2015`
3. Added a `githooks` to create a final build and push the `dist` folder to Github ( since I am not publishing on npm)

Happy to create a PR, but I am not sure if author really wants all the changes.

**Comment by rigor789** [comment]
I have a fork published to npm at `@rigor789/remark-autolink-headings`, I don't think the author uses this package anymore, so by the looks of it it has been abandoned.

**Pull request closed without merging**
